export const timeFormat = 'YYYY-MM-DD'
export const defaultOrderBy = 'date'

export const movementList = [
  'barbell bench press',
  'incline barbell bench press',
  'dumbbell bench press',
  'incline dumbbell bench press',
  'weighted dips for chest',
  'decline bench press',
  'barbell deadlift',
  'bent-over barbell row',
  'weighted pull-ups',
  'wide-grip pull-up',
  'standing t-bar row',
  'wide-grip pulldown',
  'close-grip pulldown',
  'seated cable row',
  'cable crunch',
  'hanging dumbbell knee raise',
  'landmine',
  'captain’s chair leg raise',
  'ab-wheel rollout',
  'plank',
  'weighted decline sit-up',
  'bicycle',
  'flag',
  'standing barbell overhead press',
  'seated dumbbell overhead press',
  'arnold shoulder press',
  'bent-over reverse fly',
  'lateral raise',
  'front dumbbell raise',
  'handstand push-ups',
  'barbell squat',
  'standing calf raise',
  'calf press',
  'romanian deadlift',
  'leg press',
  'hack squat',
  'dumbbell lunge',
  'seated hammer curl',
  'standing barbell curl',
  'inverted rows',
  'zottman curl',
  'weighted chin-ups',
  'incline-bench curl',
  'preacher ez-bar curl',
  'standing cable curl',
  'close-grip bench press',
  'skullcrusher',
  'weighted dips',
  'cable push-down',
  'dumbbell kickback',
  'seated overhead dumbbell extension',
  'dumbbell bench press',
  'incline dumbbell bench press',
  'weighted pull-ups',
  'hanging dumbbell knee raise',
  'weighted decline sit-up',
  'seated dumbbell overhead press',
  'arnold shoulder press',
  'bent-over reverse fly',
  'lateral raise',
  'front dumbbell raise',
  'seated hammer curl',
  'zottman curl',
  'dumbbell lunge',
  'skullcrusher',
  'weighted dips',
  'dumbbell kickback',
  'seated overhead dumbbell extension'
]

export const tagList = [
  'core',
  'arms',
  'back',
  'chest',
  'legs',
  'shoulders',
  'other',
  'olympic',
  'full body',
  'cardio',
]